org: ${env:SERVERLESS_ORG}

service: ${env:SERVERLESS_SERVICE}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  iam:
    role: ${env:AWS_ROLE}

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  allReservations:
    handler: functions/Employee/allReservations/index.handler
    events:
      - httpApi:
          path: /bonzai/emp/reservation
          method: GET
  makeReservation:
    handler: functions/Guest/makeReservation/index.handler
    events:
      - httpApi:
          path: "/bonzai/guest/boka"
          method: POST
  cancelReservation:
    handler: functions/Guest/cancelReservation/index.handler
    events:
      - httpApi:
          path: /bonzai/guest/avboka
          method: DELETE

  # dateReservations:
  #   handler: functions/Employee/dateReservations/index.handler
  #   events:
  #     - httpApi:
  #         path: "/bonzai/emp/reservation/{date}"
  #         method: GET
  # roomReservation:
  #   handler: functions/Employee/roomReservation/index.handler
  #   events:
  #     - httpApi:
  #         path: "/bonzai/emp/reservation/{id}"
  #         method: GET
  # remakeReservation:
  #   handler: functions/Guest/remakeReservation/index.handler
  #   events:
  #     - httpApi:
  #         path: "/bonzai/guest/omboka"
  #         method: PUT

resources:
  Resources:
    BonzaiBooking:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME_BOOKINGS}
        AttributeDefinitions:
          - AttributeName: BookingId
            AttributeType: "S"
        KeySchema:
          - AttributeName: BookingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    BonzaiRooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME_ROOMS}
        AttributeDefinitions:
          - AttributeName: roomId
            AttributeType: "S"
          - AttributeName: date
            AttributeType: "S"
        KeySchema:
          - AttributeName: roomId
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
