
org: egilramsten

service: Bonzai
    
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1

build:
  esbuild:
    minify: true

package:
  individually: true

functions:



resources:
  Resources:
    BonzaiBooking:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Bookings
        AttributeDefinitions:
          - AttributeName: BookingId
            AttributeType: "S"
        KeySchema:
          - AttributeName: BookingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    BonzaiRooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Rooms
        AttributeDefinitions:
          - AttributeName: roomId
            AttributeType: "S"
          - AttributeName: date
            AttributeType: "S"         
        KeySchema:
          - AttributeName: roomId
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST