
org: egilramsten

service: Bonzai
    
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam: 
    role: arn:aws:iam::390403901188:role/lambda-tester

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  allReservations:
    handler: /functions/Employee/allReservations/index.handler
    events:
      - httpApi:
          path: "/bonzai/emp/reservation"
          method: GET
  # dateReservations:
  #   handler: functions/Employee/dateReservations/index.handler
  #   events:
  #     - httpApi:
  #         path: "/bonzai/emp/reservation/{date}"
  #         method: GET
  # roomReservation:
  #   handler: functions/Employee/roomReservation/index.handler
  #   events:
  #     - httpApi:
  #         path: "/bonzai/emp/reservation/{id}"
  #         method: GET
  # cancelReservation:
  #   handler: functions/Guest/cancelReservation/index.handler
  #   events:
  #     - httpApi:
  #         path: "/bonzai/guest/avboka"
  #         method: DELETE
  makeReservation:
    handler: /functions/Guest/makeReservation/index.handler
    events:
      - httpApi:
          path: "/bonazi/guest/boka"
          method: POST
  # remakeReservation:
  #   handler: functions/Guest/remakeReservation/index.handler
  #   events:
  #     - httpApi:
  #         path: "/bonzai/guest/omboka"
  #         method: PUT
          

resources:
  Resources:
    BonzaiBooking:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Bookings
        AttributeDefinitions:
          - AttributeName: BookingId
            AttributeType: "S"
        KeySchema:
          - AttributeName: BookingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    BonzaiRooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Rooms
        AttributeDefinitions:
          - AttributeName: roomId
            AttributeType: "S"
          - AttributeName: date
            AttributeType: "S"         
        KeySchema:
          - AttributeName: roomId
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST